**Exercise Week 9**

**Author: Ahmad Ichsan Baihaqi**

**Email: ahmadichsanbaihaqi@gmail.com**

### Question 1 

In [5]:
import numpy as np

Your function will be called `display_max`. Your input will be a `numpy array`. Your output will be to tell us at which index is the maximum value of each row. Separate your output for each row with commas.

If there are more than one maximum values, only tell us the position of the FIRST occurence. 

#### Example 1

Input array: `[[1,2,3,4,3], [5,10,8,3,2], [-5,7,8.4,1,0]]`

Output: 3, 1, 2

Explanation:

- The first row, `[1,2,3,4,3]`, has the maximum value of `4` at index = 3 (Remember! This is Python. Index starts at 0)

- The second row, `[5,10,8,3,2]`, has the maximum value of `10` at index = 1

- The third row, `[-5,7,8.4,1,0]`, has the maximum value of `8.4` at index = 2

So, your output should be '3,1,2'

#### Example 2

Input array = `[[5,10,1,3], [1,5,1,5], [0,3,1,8]]`

Output: 1,1,3

Explanation:

- The first row, `[5,10,1,3]` has the maximum value of `10` at index = 1
- The second row, `[1,5,1,5]` has the maximum value of `5` at index = 1, 3. But we only need to print the first occurence, so we only print index = 1. 
- The third row, `[0,3,1,8]` has the maximum value of `8` at index = 3.

So, your output should be '1,1,3'

#### Constrains:
- Number of rows could be any integer. We can have input array of any shape and sizes. 

In [19]:
def display_max(input_array):
    max_index = []
    
    for item in input_array:
        max_value = max(item)
        
        max_value_index = item.index(max_value)
        
        max_index.append(max_value_index)
        
    return (','.join([str(int) for int in max_index]))

In [20]:
display_max([[1,2,3,4,3], [5,10,8,3,2], [-5,7,8.4,1,0]])

'3,1,2'

In [21]:
display_max([[5,10,1,3], [1,5,1,5], [0,3,1,8]])

'1,1,3'

### Numpy Question 2 


##### Reminder for Class Managers and Students. ####

If the solution has looping `for`, `while`, you do not get full points. The aim of this exercise is to avoid looping while doing things that require certain conditions.

#### Instructions: ####

Your function should be called `grade`. Your input will be an array where each rows shows the score of a student. Your output will be an array WITH THE EXACT SAME SIZE as the input array, but only filled with 'P' and 'F'.

- If the score is >= 70, then for that test, the student passes. We give the symbol 'P' to indicate that the student passes.
- If the score is < 70, then for that test, the student fails. We give the symbol 'F', to indicate that the student fails.

#### Example 1:

In [28]:
input_array1 = np.array([[80,50,80,60,70],
                       [100,90,80,70,50],
                       [70,70,60,50,85]])
input_array1

array([[ 80,  50,  80,  60,  70],
       [100,  90,  80,  70,  50],
       [ 70,  70,  60,  50,  85]])

If the input is like the above array, then it means we have `3` students. Each student has `5` scores.

- The first student's scores are: 80, 50, 80, 60, 70. From first to last, the student Pass, Fail, Pass, Fail, Pass
- The second student's scores are: 100, 90, 80, 70, 50. From first to last, the student Pass, Pass, Pass, Pass, Fail
- The third student's scores are: 70, 70, 60, 50, 80. From first to last, the student Pass, Pass, Fail, Fail, Pass

Then, when you do `grade(input_array)`,  your output should be like this:
`[[P,F,P,F,P],[P,P,P,P,F],[P,P,F,F,P]]`

#### Example 2:

In [29]:
input_array2 = np.array([[100,50,100],
                       [70,70,70],
                       [40,80,40],
                       [50,55,80]])
input_array2

array([[100,  50, 100],
       [ 70,  70,  70],
       [ 40,  80,  40],
       [ 50,  55,  80]])

If the input is like the above array, then it means we have `4` students. Each student has `3` scores. Then, when you do `grade(input_array)`,  your output should be like this:

`[[P,F,P], [P,P,P], [F,P,F], [F,F,P]]`

In [30]:
def grade(input_array):
    return np.where(input_array >= 70, "P", "F").tolist()

In [31]:
grade(input_array1)

[['P', 'F', 'P', 'F', 'P'],
 ['P', 'P', 'P', 'P', 'F'],
 ['P', 'P', 'F', 'F', 'P']]

In [32]:
grade(input_array2)

[['P', 'F', 'P'], ['P', 'P', 'P'], ['F', 'P', 'F'], ['F', 'F', 'P']]

### Numpy Question 3 

Your function name should be called `one_hot`, and the input of your function is a numpy array. 

In this task, you are asked to convert an array of integers into one hot encoding. 

This is useful in machine learning and even deep learning cases, in which we want to do feature engineering, represent categorical classes, etc. 

Resource on one-hot-encoding: https://machinelearningmastery.com/why-one-hot-encode-data-in-machine-learning/

#### Example 1:

If the input array is `[2,3,1,2]` then the one-hot encoding version of it is: 

`[[0,1,0], [0,0,1], [1,0,0], [0,1,0]]`

Explanation: there are 3 unique integers: 1, 2, and 3. If we want to represent them with one-hot encoding, we have to represent them in `0 and 1`. 

Because there are 3 unique integers, we represent them in 3 sequences of `0 and 1`. 

1 is represented as `[1, 0, 0]`
2 is represented as `[0, 1, 0]`
3 is represented as `[0, 0, 1]`

So, if the `input_array` is `np.array([2,3,1,2])`
And the array is passed into your function..

`one_hot(input_array)` equals to `array([[0,1,0], [0,0,1], [1,0,0], [0,1,0]])`

#### Example 2

If the input array is `[4,2,1,3]` then the one-hot encoding version of it is: 

`[[0,0,0,1], [0,1,0,0], [1,0,0,0], [0,0,1,0]]`

Explanation: there are 4 unique integers: 1, 2, 3, and 4. If we want to represent them with one-hot encoding, we have to represent them in `0 and 1`. 

Because there are 4 unique integers, we represent them in 4 sequences of `0 and 1`. 

1 is represented as `[1, 0, 0, 0]`
2 is represented as `[0, 1, 0, 0]`
3 is represented as `[0, 0, 1, 0]`
4 is represented as `[0, 0, 0, 1]`

So, if the `input_array` is `np.array([4,2,1,3])`
And the array is passed into your function..

`one_hot(input_array)` equals to `array([[0,0,0,1], [0,1,0,0], [1,0,0,0], [0,0,1,0]])`


#### Constrains:

- Integers in the input array will start with 1. 
- Integers in the input array will not be zero or negative numbers.
- Integers will not be skipped (for example, it is impossible for the input array to have [4,1,2] because 3 is missing).



In [97]:
from numpy import array
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [98]:
def one_hot(input_array):
    # define example
    values = np.array(input_array)

    # integer encode
    label_encoder = LabelEncoder()
    integer_encoded = label_encoder.fit_transform(values)

    # binary encode
    onehot_encoder = OneHotEncoder(sparse=False)
    integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
    onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
    
    return onehot_encoded

In [99]:
one_hot([4,2,1,3])

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [100]:
one_hot([2,3,1,2])

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])